/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/7.0.68
 * Generated at: 2017-11-10 17:29:51 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp.WEB_002dINF.page.hospital.common;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;

public final class head_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent {

  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  private volatile javax.el.ExpressionFactory _el_expressionfactory;
  private volatile org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public javax.el.ExpressionFactory _jsp_getExpressionFactory() {
    if (_el_expressionfactory == null) {
      synchronized (this) {
        if (_el_expressionfactory == null) {
          _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
        }
      }
    }
    return _el_expressionfactory;
  }

  public org.apache.tomcat.InstanceManager _jsp_getInstanceManager() {
    if (_jsp_instancemanager == null) {
      synchronized (this) {
        if (_jsp_instancemanager == null) {
          _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
        }
      }
    }
    return _jsp_instancemanager;
  }

  public void _jspInit() {
  }

  public void _jspDestroy() {
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
        throws java.io.IOException, javax.servlet.ServletException {

    final javax.servlet.jsp.PageContext pageContext;
    javax.servlet.http.HttpSession session = null;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html; charset=UTF-8");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("\r\n");
      out.write(" <header class=\"enroll_header\">\r\n");
      out.write("      <a href=\"javascript:;\" style=\"color: #000;\" onclick=\"lxwmShow();\" title=\"\">联系我们</a>\r\n");
      out.write("      <a href=\"#\" style=\"color: #000;\"  title=\"\"> 医院后台入口\r\n");
      out.write("      </a>\r\n");
      out.write("        <a href=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${pageContext.request.contextPath}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null, false));
      out.write("/admin\" style=\"color: #000;\"  title=\"\"> 美滴滴管理入口\r\n");
      out.write("      </a>\r\n");
      out.write("        <a href=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${pageContext.request.contextPath}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null, false));
      out.write("/consult/out\" style=\"color: #000;\"  title=\"\"> 咨询师入口\r\n");
      out.write("      </a>\r\n");
      out.write("      \r\n");
      out.write("      <div class=\"meidd_logo\">\r\n");
      out.write("          <a href=\"\" title=\"美滴滴中国专业整形咨询平台\">\r\n");
      out.write("              <img src=\"assets/images/index_logo2.png\" alt=\"\">\r\n");
      out.write("          </a>\r\n");
      out.write("      </div>\r\n");
      out.write("</header>\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("<script>\r\n");
      out.write("var lxwm = dialog({\r\n");
      out.write("    content: '<div class=\"popup_box\">'\r\n");
      out.write("\t+\t'<cite class=\"popup_t\">联系我们</cite>'\r\n");
      out.write("\t+\t'<div class=\"popup_cont\">'\r\n");
      out.write("\t+\t\t'<div class=\"contact_us\">'\r\n");
      out.write("        +                       '<div class=\"search_box\"></div>'\r\n");
      out.write("\t+\t\t\t'<div class=\"sh_plan_inquire\">'\r\n");
      out.write("\t+\t\t\t\t'<form class=\"form-search\">'\r\n");
      out.write("\t+\t\t\t\t\t'<label>注册审核进度查询</label>'\r\n");
      out.write("\t+\t\t\t\t\t'<input type=\"text\" class=\"input_plan_search\" placeholder=\"请输入注册时填写提交的手机号\" value=\"\" name=\"\" id=\"resPhone\">'\r\n");
      out.write("\t+\t\t\t\t\t'<input type=\"button\" class=\"btn_search\" value=\"查询\" onclick=\"tolxwm();\">'\r\n");
      out.write("\t+\t\t\t\t'</form>'\r\n");
      out.write("\t+\t\t\t'</div>'\r\n");
      out.write("\t+\t\t\t'<div class=\"contact_box\">'\r\n");
      out.write("\t+\t\t\t\t'<p>服务电话&nbsp;400-807-5989</p>'\r\n");
      out.write("\t+\t\t\t\t'<p>服务邮箱&nbsp;support@meididi.com.cn</p>'\r\n");
      out.write("\t+\t\t\t'</div>'\r\n");
      out.write("\t+\t\t'</div>'\r\n");
      out.write("\t+\t\t'<p class=\"popup_btn\">'\r\n");
      out.write("\t+\t\t\t'<span class=\"popup_btn_p\">'\r\n");
      out.write("\t+\t\t\t\t'<input type=\"button\" value=\"返回\" class=\"input_green\" onclick=\"lxwmOff();\" />'\r\n");
      out.write("\t+\t\t\t'</span></p></div>'\r\n");
      out.write("\t+'</div>'\r\n");
      out.write("\t\t\r\n");
      out.write("    });\r\n");
      out.write("\r\n");
      out.write("function lxwmShow(){\r\n");
      out.write("    $(\".popup_bg\").show();\r\n");
      out.write("    $(\"#resPhone\").val('');\r\n");
      out.write("    $(\".search_box\").html('');\r\n");
      out.write("    lxwm.show();\r\n");
      out.write("}\r\n");
      out.write("function lxwmOff(){\r\n");
      out.write("    $(\".popup_bg\").hide();\r\n");
      out.write("    lxwm.close();\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write("function tolxwm(){\r\n");
      out.write("    var resPhone=$(\"#resPhone\").val();\r\n");
      out.write("    if(resPhone==''){\r\n");
      out.write("        alert('请填写手机号');\r\n");
      out.write("    }else{\r\n");
      out.write("         var reg = /^0?1[0-9]{10}$/;\r\n");
      out.write("             if (reg.test(resPhone)) {\r\n");
      out.write("                 $.ajax({\r\n");
      out.write("                   url:\"account_process\",\r\n");
      out.write("                   type:'POST',\r\n");
      out.write("                   timeout:3000,\r\n");
      out.write("                   data : {phone:resPhone},\r\n");
      out.write("                   success:function(data){\r\n");
      out.write("                \t   var json = $.parseJSON(data);\r\n");
      out.write("                       if(json.msg==\"success\"){\r\n");
      out.write("                            var str_1='<span class=\"ico_audit\">!</span><p class=\"c_pink\">'+json.name+'</p><p class=\"c_e\">正在审核中</p>';\r\n");
      out.write("                            var str_2='<span class=\"ico_audit_pass\">√</span><p class=\"c_pink\">'+json.name+'</p>'\r\n");
      out.write("\t\t\t\t\t+'<p class=\"c_e f16\">审核已通过<a href=\"'+''+'\" title=\"\" class=\"mail_alink\" target=\"_blank\">去邮箱</a></p>';\r\n");
      out.write("                            var str_3='<span class=\"ico_audit_notpass\">×</span><p class=\"c_pink\">'+json.name+'</p><p class=\"c_e f16\">审核未通过<a href=\"javascript:;\" title=\"\" class=\"mail_alink\" onclick=\"javascript: window.open(\\''+''+'\\')\">去邮箱</a></p>';\r\n");
      out.write("                            if(json.state==\"-1\"){\r\n");
      out.write("                            \t$(\".search_box\").html(str_1);\r\n");
      out.write("                            }\r\n");
      out.write("                            if(json.state==\"1\"){\r\n");
      out.write("                            \t$(\".search_box\").html(str_2);\r\n");
      out.write("                            }\r\n");
      out.write("                            if(json.state==\"0\"){\r\n");
      out.write("                            \t$(\".search_box\").html(str_3);\r\n");
      out.write("                            }\r\n");
      out.write("                            \r\n");
      out.write("                           \r\n");
      out.write("                        }else{\r\n");
      out.write("                            alert(\"请填写正确的手机号\");\r\n");
      out.write("                        }\r\n");
      out.write("\r\n");
      out.write("                   }\r\n");
      out.write("                });\r\n");
      out.write("             }else{\r\n");
      out.write("                 alert(\"请填写正确的手机号\");\r\n");
      out.write("             }\r\n");
      out.write("    }\r\n");
      out.write(" \r\n");
      out.write("    \r\n");
      out.write("}\r\n");
      out.write("</script>");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }
}
