/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/7.0.68
 * Generated at: 2017-11-10 17:29:51 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp.WEB_002dINF.page;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;

public final class log_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent {

  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  private volatile javax.el.ExpressionFactory _el_expressionfactory;
  private volatile org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public javax.el.ExpressionFactory _jsp_getExpressionFactory() {
    if (_el_expressionfactory == null) {
      synchronized (this) {
        if (_el_expressionfactory == null) {
          _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
        }
      }
    }
    return _el_expressionfactory;
  }

  public org.apache.tomcat.InstanceManager _jsp_getInstanceManager() {
    if (_jsp_instancemanager == null) {
      synchronized (this) {
        if (_jsp_instancemanager == null) {
          _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
        }
      }
    }
    return _jsp_instancemanager;
  }

  public void _jspInit() {
  }

  public void _jspDestroy() {
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
        throws java.io.IOException, javax.servlet.ServletException {

    final javax.servlet.jsp.PageContext pageContext;
    javax.servlet.http.HttpSession session = null;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html; charset=UTF-8");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");

String path = request.getContextPath();
String basePath = request.getScheme()+"://"+request.getServerName()+":"+request.getServerPort()+path+"/";

      out.write("\r\n");
      out.write("<!DOCTYPE html>\r\n");
      out.write("<html>\r\n");
      out.write("<head>\r\n");
      out.write("\t<meta http-equiv=\"Content-Type\" content=\"text/html; charset=utf-8\" />\r\n");
      out.write("\t<meta http-equiv=\"X-UA-Compatible\" content=\"IE=edge,chrome=1\" />\r\n");
      out.write("\t<meta name=\"renderer\" content=\"webkit|ie-comp|ie-stand\">\r\n");
      out.write("\t<base href=\"");
      out.print(basePath);
      out.write("\">\r\n");
      out.write("\t<link rel=\"stylesheet\" type=\"text/css\" href=\"assets/css/hospital/screen.css\" media=\"screen, projection\" />\r\n");
      out.write("\t<link rel=\"stylesheet\" type=\"text/css\" href=\"assets/css/hospital/print.css\" media=\"print\" />\r\n");
      out.write("\t<link rel=\"stylesheet\" type=\"text/css\" href=\"assets/css/hospital/base.css\"  />\r\n");
      out.write("\t<link rel=\"stylesheet\" type=\"text/css\" href=\"assets/css/hospital/popup.css\"  />\r\n");
      out.write("\t<link rel=\"stylesheet\" type=\"text/css\" href=\"assets/css/hospital/main.css\" />\r\n");
      out.write("\t<link rel=\"stylesheet\" type=\"text/css\" href=\"assets/css/bootstrap.min.css\"  />\r\n");
      out.write("\t<link rel=\"stylesheet\" type=\"text/css\" href=\"assets/css/ui-dialog.css\"  />\r\n");
      out.write("\t<!--[if lt IE 8]>\r\n");
      out.write("\t<link rel=\"stylesheet\" type=\"text/css\" href=\"css/ie.css\" media=\"screen, projection\" />\r\n");
      out.write("\t<![endif]-->\r\n");
      out.write("\r\n");
      out.write("\t<script type=\"text/javascript\" src=\"assets/js/jquery.min.js\"></script>\r\n");
      out.write("\r\n");
      out.write("\t<title>美滴滴-为用户定制全程一对一实时在线咨询服务专业的整形医美咨询平台</title>\r\n");
      out.write("    <script src=\"assets/js/sea.js\"></script>\r\n");
      out.write("\t<script src=\"assets/js/seajs-config.js\"></script>\r\n");
      out.write("\t<script src=\"assets/js/dialog-min.js\"></script>\r\n");
      out.write("\t<script src=\"assets/js/hospital/reg.js\"></script>\r\n");
      out.write("    <style type=\"text/css\">\r\n");
      out.write("    \t.popup_bg~header{\r\n");
      out.write("    \t\tbackground: none;\r\n");
      out.write("    \t}\r\n");
      out.write("    </style>\r\n");
      out.write("</head>\r\n");
      out.write("<body class=\"\">\r\n");
      out.write("    <div class=\"popup_bg\" style=\"display: none;z-index: 1;\"></div>\r\n");
      out.write("\t");
      org.apache.jasper.runtime.JspRuntimeLibrary.include(request, response, "hospital/common/head.jsp", out, false);
      out.write("\r\n");
      out.write("\t<div class=\"index_cont\">\r\n");
      out.write("\t\t<div class=\"index_text\">\r\n");
      out.write("\t\t\t<img src=\"assets/images/hospital/text_welcome.png\">\r\n");
      out.write("\t\t\t<p>欢迎回来！我的美容机构合作伙伴！</p>\r\n");
      out.write("\t\t\t<h1>我们！</h1>\r\n");
      out.write("\t\t\t<h1>因美丽相聚</h1>\r\n");
      out.write("\t\t\t<h1>共同开创事业……</h1>\r\n");
      out.write("\t\t</div>\r\n");
      out.write("\t\t<div class=\"index_btn\">\r\n");
      out.write("            <a href=\"javascript:void(0);\" title=\"我要登录\" class=\"input_green mr20\" onclick=\"loginShow();\">我要登录</a>\r\n");
      out.write("            <a href=\"account_reg\" title=\"我要注册\" class=\"btn_b_green c_brown\">我要注册</a>\r\n");
      out.write("\t\t</div>\r\n");
      out.write("\t</div>\r\n");
      out.write("\t<footer class=\"footer_box\" style=\"position:fixed;bottom: 0px; margin-top: 34px;\">北京漾世代科技有限公司     京ICP备16003557号</footer>\r\n");
      out.write("\t<img alt=\"\" src=\"assets/images/hospital/index_bg.jpg\" style=\"position:fixed;left:0;top:0;right:0;bottom:0;width:100%;height:100%;z-index:-11;\">\r\n");
      out.write("\t<script type=\"text/javascript\">\r\n");
      out.write("\t$().ready(function(){\r\n");
      out.write("\t\tif (window.frames.length != parent.frames.length) {  \r\n");
      out.write("\t         //alert('在iframe中');\r\n");
      out.write("\t         window.parent.location.href=\"index\";\r\n");
      out.write("\t\t}\r\n");
      out.write("\t});\r\n");
      out.write("var d = dialog({\r\n");
      out.write("    content: '<div class=\"popup_box\"><cite class=\"popup_t\">登录</cite><div class=\"popup_cont\"><div class=\"index_logoin_box\"><p class=\"login_hint\">忘记账号或密码请联系医院平台管理员</p><input id=\"username\" type=\"text\" placeholder=\"请输入登录账号\" name=\"LoginForm[username]\"><input id=\"password\" type=\"password\" placeholder=\"请输入登录密码\" name=\"LoginForm[password]\"><div class=\"login_captcha\"></div></form></div><p class=\"popup_btn\"><input type=\"button\" value=\"取消\" class=\"input_green mt25 mr20\" onclick=\"loginOff();\"/><input type=\"button\" value=\"登录\" class=\"input_green mt25\" onclick=\"toLogin();\"/></p></div></div>'\r\n");
      out.write("});\r\n");
      out.write("function loginShow(){\r\n");
      out.write("    $(\".popup_bg\").show();\r\n");
      out.write("   \r\n");
      out.write("    d.show();\r\n");
      out.write("}\r\n");
      out.write("function loginOff(){\r\n");
      out.write("    $(\".popup_bg\").hide();\r\n");
      out.write("   \r\n");
      out.write("    d.close();\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write("function toLogin(){\r\n");
      out.write("    \r\n");
      out.write("    var name=$(\"#username\").val();\r\n");
      out.write("    var password=$(\"#password\").val();\r\n");
      out.write("    if(name==''){\r\n");
      out.write("        $(\"#username\").addClass('error_code');\r\n");
      out.write("        return false;\r\n");
      out.write("    }\r\n");
      out.write("    if(password==''){\r\n");
      out.write("        $(\"#password\").addClass('error_code');\r\n");
      out.write("        return false;\r\n");
      out.write("    }\r\n");
      out.write("\r\n");
      out.write("    //$(\"#login_form\").submit();\r\n");
      out.write("    $.ajax({\r\n");
      out.write("\t\turl:\"login\",\r\n");
      out.write("\t\ttype:'POST',\r\n");
      out.write("\t\ttimeout:3000,\r\n");
      out.write("\t\tdata : {\"hospitalAccount.accounts\":name,\"hospitalAccount.password\":password},\r\n");
      out.write("\t\tsuccess:function(data){\r\n");
      out.write("        \tif(data==\"success\"){\r\n");
      out.write("            \t$(\".popup_bg\").hide();\r\n");
      out.write("             \td.close();\r\n");
      out.write("                window.location.href=\"hospital/index\"; \r\n");
      out.write("            }else{\r\n");
      out.write("                 $(\".login_hint\").html(\"登录失败\");\r\n");
      out.write("            }\r\n");
      out.write("\r\n");
      out.write("           }\r\n");
      out.write("      });\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("$(document).keydown(function(e) {\r\n");
      out.write("\tif (e.keyCode == 13){\r\n");
      out.write("\t\ttoLogin();\r\n");
      out.write(" \t}\r\n");
      out.write("\t});\r\n");
      out.write("</script>\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("</body>\r\n");
      out.write("</html>");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }
}
